/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tweet.java
 *
 * Created on Apr 8, 2010, 4:57:42 AM
 */



import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;

import twitter4j.*;

import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Sophia
 */
public class tweet extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/** Creates new form login */
    public tweet() {
        initComponents();

        
        int loginWidth = twitterLogin.getPreferredSize().width;
        int loginHeight = twitterLogin.getPreferredSize().height;
        twitterLogin.setBounds(0,0,loginWidth,loginHeight);
        twitterLogin.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        twitterLogin = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        twitterLogin.setTitle("TwitterLogin");
        twitterLogin.setModal(true);

        javax.swing.GroupLayout twitterLoginLayout = new javax.swing.GroupLayout(twitterLogin.getContentPane());
        twitterLogin.getContentPane().setLayout(twitterLoginLayout);
        twitterLoginLayout.setHorizontalGroup(
            twitterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        twitterLoginLayout.setVerticalGroup(
            twitterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TwitterLogin");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
       try {
           twitter = new Twitter(txtUsername.getText(),String.valueOf(txtPassword.getPassword()));
           twitter.verifyCredentials();
           //JOptionPane.showMessageDialog(null,"You are logged in!");
           java.util.List<Status> statusList=twitter.getUserTimeline();
           for (int i=0;i<statusList.size();i++) {
                    jTextArea1.append(String.valueOf(statusList.get(i).getText())+"\n");
                    jTextArea1.append("-----------------------------\n");
                    
           }
           twitterLogin.dispose();
       } catch(TwitterException e) {
           JOptionPane.showMessageDialog(null,"Login Failed");

       }
       jTextArea1.updateUI();
       
       try {

       	java.util.List<Status> statusList = twitter.getFriendsTimeline();

       	jPanel1.setLayout(new GridLayout(statusList.size(),1));

       	for (int i=0; i<statusList.size(); i++) {

       	statusText = new JLabel(String.valueOf(statusList.get(i).getText()));

       	statusUser = new JLabel(statusList.get(i).getUser().getName());
       	Font newLabelFont = new Font(statusUser.getFont().getName(),Font.PLAIN,statusUser.getFont().getSize());
       	statusText.setFont(newLabelFont);

       	JPanel individualStatus = new JPanel(new GridLayout(2,1));

       	individualStatus.add(statusUser);

       	individualStatus.add(statusText);
       	individualStatus.setBorder(BorderFactory.createLineBorder(Color.black));

       	jPanel1.add(individualStatus);

       	}

       	} catch (TwitterException e) {

       	JOptionPane.showMessageDialog (null, "A Twitter error ocurred!");}

       	jPanel1.updateUI();
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {
       System.exit(0);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tweet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDialog twitterLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jPanel1;

   
    // End of variables declaration


     Twitter twitter;
     JLabel statusText;

     JLabel statusUser;
}
